package action_request_response;

public enum Commands {
    CASHOUT,
    ADDEXPENSE,
    COMPAREBUDGET,
    CREATEBOND,
    CREATESAVINGS,
    CREATEUSER,
    DEPOSIT,
    DEPOSITSAVINGS,
    DISPLAYSAVINGS,
    DISPLAYDEPOSITRECCORD,
    DISPLAYWITHDRAWALRECORD,
    LOGIN,
    OWNERINFO,
    SIMULATE,
    STOREDATAInJSON,
    UPDATEDEPOSITABLE,
    USERQUIT,
    VIEWINVESTMENTS,
    WITHDRAWAL,
    STOREDATAINJSON,
    RESETBUDGET,
    ADJUSTBUDGET,
    VIEWBUDGETPERFORMANCE
}
