package action_request_response;

public enum Commands {
    CALCULATEREMAININGBUDGET,
    CASHOUT,
    CREATEBOND,
    CREATESAVINGS,
    CREATEUSER,
    DEPOSIT,
    DEPOSITSAVINGS,
    DISPLAYDEPOSITRECCORD,
    DISPLAYBUDGET,
    DISPLAYWITHDRAWALRECORD,
    LOGIN,
    OWNERINFO,
    SIMULATE,
    UPDATEDEPOSITABLE,
    TRANSFER,
    USERQUIT,
    VIEWINVESTMENTS,
    WITHDRAWAL,
    RESETBUDGET,
    ADJUSTBUDGET,
    VIEWBUDGETPERFORMANCE
}
